import '../styles/globals.css'
import 'primereact/resources/themes/tailwind-light/theme.css';

import Menu from '../components/Menu'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Menu />
        {children}
      </body>
    </html>
  )
}